"""Initial migration

Revision ID: 915353d6f478
Revises: 
Create Date: 2024-10-24 23:17:16.794417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915353d6f478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landlord_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('number_of_rooms', sa.Integer(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('house_number', sa.String(length=10), nullable=False),
    sa.Column('occupied_rooms', sa.Integer(), nullable=False),
    sa.Column('price_bedsitter', sa.Float(), nullable=True),
    sa.Column('price_one_bedroom', sa.Float(), nullable=True),
    sa.Column('price_two_bedroom', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(length=100), nullable=False),
    sa.Column('tenant_phone_number', sa.String(length=20), nullable=False),
    sa.Column('house_number', sa.String(length=10), nullable=False),
    sa.Column('house_type', sa.String(length=50), nullable=False),
    sa.Column('deposit_paid', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('receipt_number_deposit', sa.String(length=100), nullable=True),
    sa.Column('rent_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('rent_receipt_number', sa.String(length=100), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('rent_paid', sa.Float(), nullable=True),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number_deposit'),
    sa.UniqueConstraint('rent_receipt_number'),
    sa.UniqueConstraint('tenant_phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant')
    op.drop_table('property')
    op.drop_table('user')
    op.drop_table('landlord')
    # ### end Alembic commands ###
